###consul服务端口号
server:
  port: 80

spring:
  application:
    name: consul-consumer-order
  ####consul注册中心地址
  cloud:
    consul:
      host: 47.104.102.96
      port: 8500
      discovery:
#        hostname: 192.168.3.10
        service-name: ${spring.application.name}
        health-check-url: http://304w12047j.imdo.co/actuator/health
